In [23]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

In [24]:
df2023 = pd.read_csv('/Users/daynakarls/Library/CloudStorage/OneDrive-UW-Madison/Biokind Analytics/2023 Annual Campaign - Active.csv')

,Donation ID,Account ID,Shopping Cart ID,Campaign ID,Donation Amount,Donation Date,Account Type,Full Name (F),Company Name,City,Address Line 1,State/Province,Zip Code,Campaign Name,Purpose,Fund,Tender Type,Tribute Full Name (F),Unnamed: 18
0,6442,1600,6494,12,26.08,02/23/2023,Individual,Barbara Amato,NaN,NaN,NaN,NaN,53562,2023 Annual Campaign,General Operating,Unrestricted,Credit Card (Online),NaN,NaN
1,6491,5751,6543,12,51.85,02/23/2023,Individual,Karen Anderson,NaN,"WATERLOO, WI",167 COUNTY ROAD TV,WI,53594,2023 Annual Campaign,General Operating,Unrestricted,Credit Card (Online),NaN,NaN
2,6990,5933,7055,12,50000.00,10/26/2023,Company,Brett Lindquist,Ascendium Education Group,Madison,38 Buttonwood Ct.,WI,NaN,2023 Annual Campaign,General Operating,Unrestricted,Check,NaN,NaN
3,7019,2383,7085,12,104.69,12/30/2023,Individual,Annette and Chris Ashley,NaN,Middleton,3702 Mandimus Court,WI,53562,2023 Annual Campaign,General Operating,Unrestricted,Credit Card (Online),NaN,NaN
4,7022,4278,7088,12,750.00,12/31/2023,Individual,Amanda Bagin,NaN,DeForest,993 Clover Ln,WI,53532,2023 Annual Campaign,General Operating,Unrestricted,Credit Card (Online),NaN,NaN

In [26]:
df2022 = pd.read_csv('/Users/daynakarls/Library/CloudStorage/OneDrive-UW-Madison/Biokind Analytics/2022 Annual Campaign - Active.csv')

,Donation ID,Account ID,Shopping Cart ID,Campaign ID,Donation Amount,Donation Date,Account Type,Full Name (F),Company Name,City,Address Line 1,State/Province,Zip Code,Campaign Name,Purpose,Fund,Tender Type,Tribute Full Name (F),Unnamed: 18
0,3701,3342,3753,9,103.30,02/24/2022,Individual,John Anderson,NaN,Wisconsin Dells,879 South Grouse Ct,WI,53965,2022 Annual Campaign,NaN,Unrestricted,Credit Card (Online),NaN,NaN
1,4662,4221,4714,9,51.80,05/15/2022,Individual,Taylor Andrews,NaN,NaN,NaN,NaN,53593,2022 Annual Campaign,NaN,Unrestricted,Credit Card (Online),NaN,NaN
2,3479,3120,3531,9,25.00,02/24/2022,Individual,Valerie Ash,NaN,Rio,135 Athens St,WI,53960,2022 Annual Campaign,NaN,Unrestricted,PayPal,NaN,NaN
3,6571,2296,6623,9,52.39,02/25/2023,Individual,Dennis & Denise Babish,NaN,NaN,NaN,NaN,53536,2022 Annual Campaign,General Operating,Unrestricted,Credit Card (Online),NaN,NaN
4,6955,2296,7018,9,52.50,11/25/2023,Individual,Dennis & Denise Babish,NaN,NaN,NaN,NaN,53536,2022 Annual Campaign,General Operating,Unrestricted,Credit Card (Online),NaN,NaN

In [35]:
df2023['City'] = (
    df2023['City']
    .str.lower()
    .str.replace(r'[^\w\s]', '', regex=True)
    .str.strip()
)

#condensing city names, so that all of the same can be grouped together 
city_replacements = {
    'madison wi 53705 usa': 'madison',
    'madison wi': 'madison',
    'madison': 'madison',
    'verona wi': 'verona',
    'prairie du sac': 'prairie du sac',
    'waterloo wi': 'waterloo',
    'oregon wi': 'oregon',
    'cambria wi': 'cambria',
}
df2023['City'] = df2023['City'].replace(city_replacements)

#changed 'NA' rows to unknown
df2023['City'] = df2023['City'].fillna('unknown')
df2023['State/Province'] = df2023['State/Province'].fillna('unknown')

#some rows had city = madison, state = unknown, changed the state of these rows to WI, so they could be grouped with the rest of the madison rows
df2023.loc[(df2023['City'] == 'madison') & (df2023['State/Province'] == 'unknown'), 'State/Province'] = 'WI'



#grouped rows by city and state and to get total donation amount
summary_df23 = df2023.groupby(['City', 'State/Province']).agg(
    Number_of_Donors=('City', 'size'),
    Total_Donation_Amount=('Donation Amount', 'sum')
).reset_index()

               City State/Province  Number_of_Donors  Total_Donation_Amount
0        belleville             WI                 1                 103.60
1          brooklyn             WI                 1                  90.00
2           cambria             WI                 1                  51.85
3         cambridge             WI                 7                 318.32
4      cross plains             WI                 1                  12.68
5         deerfield             WI                 1                 154.93
6          deforest             WI                 2                 801.85
7        eau claire             WI                 1                  51.96
8          edgerton             WI                 1                 129.16
9        evansville             WI                 3                 177.16
10          fairfax             VA                 1                 706.39
11        fitchburg             WI                 5                 831.35
12    fort atkinson             WI                 1                  25.00
13       fort worth             TX                 1                 103.39
14       janesville             WI                 3                5041.85
15       lake mills             WI                 1                 100.00
16             lodi             WI                 1                  26.08
17      los angeles             CA                 1                 104.47
18          madison             WI                71               78628.35
19         marshall             WI                 3                  38.13
20        mcfarland             WI                 1                  26.08
21        middleton             WI                 5                3530.77
22           monona             WI                 2                  76.08
23      mount horeb             WI                 1                   5.46
24          muscoda             WI                 1                  25.00
25       new glarus             WI                 1                  51.85
26         new york             NY                 1                  51.85
27        oak creek             WI                 4                 100.00
28           oregon             WI                 5                1174.24
29      orfordville             WI                 2                 232.76
30   prairie du sac             WI                 2                  83.08
31         richmond             TX                 3                 600.00
32         rosemead             CA                 1                   5.46
33        sauk city             WI                 1                 103.39
34          seattle             WA                 2               75600.00
35         stanford             CA                 1                  12.68
36      sun prairie             WI                 6                 585.90
37          unknown             WI                 1                 103.39
38          unknown        unknown                15                6420.72
39           verona             WI                13                 811.92
40            viola             WI                 1                  10.62
41         waterloo             WI                 1                  51.85
42         waunakee             WI                 1                 300.00
43        wind lake             WI                 1                  50.00
44  wisconsin dells             WI                 1                  51.85

In [33]:
df2022['City'] = (
    df2022['City']
    .str.lower()
    .str.replace(r'[^\w\s]', '', regex=True)
    .str.strip()
)

#condensing city names, so that all of the same can be grouped together 
city_replacements = {
    'madison wi 53705 usa': 'madison',
    'madison wi': 'madison',
    'madison': 'madison',
    'verona wi': 'verona',
    'prairie du sac': 'prairie du sac',
    'waterloo wi': 'waterloo',
    'oregon wi': 'oregon',
    'cambria wi': 'cambria',
    'waukesha wisconsin ee uu' : 'waukesha',
}
df2022['City'] = df2022['City'].replace(city_replacements)

#changed 'NA' rows to unknown
df2022['City'] = df2022['City'].fillna('unknown')
df2022['State/Province'] = df2022['State/Province'].fillna('unknown')

#some rows had city = madison, state = unknown, changed the state of these rows to WI, so they could be grouped
df2022.loc[(df2022['City'] == 'madison') & (df2022['State/Province'] == 'unknown'), 'State/Province'] = 'WI'


#grouped rows by city and state and to get total donation amount
summary_df22 = df2022.groupby(['City', 'State/Province']).agg(
    Number_of_Donors=('City', 'size'),
    Total_Donation_Amount=('Donation Amount', 'sum')
).reset_index()

summary_df22

               City State/Province  Number_of_Donors  Total_Donation_Amount
0            albany             WI                 1                  26.06
1             arena             WI                 1                  26.06
2            austin             TX                 1                  51.80
3        belleville             WI                 1                  26.06
4         cambridge             WI                 6                1408.49
5   cortlandt manor             NY                 1                  25.00
6     cottage grove             WI                 2                 129.45
7      cross plains             WI                 2                  24.67
8        darlington             WI                 1                  26.06
9          deforest             WI                20                 847.16
10       eau claire             WI                 1                  51.80
11       evansville             WI                 1                  26.06
12        fitchburg             WI                 1                 103.30
13          hamburg             PA                 1                  51.80
14      hazel green             WI                 1                  51.80
15       janesville             WI                 3                 122.43
16       lake mills             WI                 1                  51.80
17          madison             WI               314               53059.40
18         marshall             WI                 2                  62.68
19        mcfarland             WI                26                2532.91
20         merrimac             WI                 1                  25.00
21        middleton             WI                68                6561.57
22           milton             WI                 1                  26.06
23           monona             WI                 1                1250.00
24     new brighton             MN                 1                 103.60
25           oregon             WI                13                 306.86
26          palmyra             WI                 1                 406.75
27         poynette             WI                 1                  51.80
28  prairie farm wi             WI                 1                 200.00
29     richland ctr             WI                 1                  12.67
30         richmond             TX                14               17993.76
31              rio             WI                 1                  25.00
32          seattle             WA                 1                  75.00
33      south wayne             WI                21                 547.64
34     spring green             WI                 1                 309.27
35        stoughton             WI                 4                 232.96
36           summit             NJ                 1                  51.80
37      sun prairie             WI                 5                5325.00
38          unknown             WI                 3                 126.80
39          unknown        unknown               171                9002.46
40           verona             WI                32               12627.53
41        watertown             WI                 2                  38.78
42         waukesha             WI                 1                  26.06
43         waunakee             WI                 2                  77.86
44  wisconsin dells             WI                 1                 103.30

In [65]:
import pandas as pd
import folium
from folium.plugins import HeatMap
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import time

# Filter for donations
data = df2022.dropna(subset=['City', 'Donation Amount'])  # Drop rows with missing data

# Aggregate donations by city
aggregated_donations = data.groupby('City')['Donation Amount'].sum().reset_index()

# Initialize geolocator
geolocator = Nominatim(user_agent="donation_heatmap")

# Geocode function to get latitude and longitude for each city
def geocode_city(city, retries=3):
    for attempt in range(retries):
        try:
            location = geolocator.geocode(f"{city}, USA", timeout=10)  # Increase timeout
            if location:
                return location.latitude, location.longitude
            else:
                return None, None
        except GeocoderTimedOut:
            if attempt < retries - 1:
                time.sleep(2)  # Wait before retrying
                continue
            return None, None

# Add latitude and longitude columns
aggregated_donations[['Latitude', 'Longitude']] = aggregated_donations['City'].apply(
    lambda city: pd.Series(geocode_city(city))
)

# Drop rows where geocoding failed
aggregated_donations = aggregated_donations.dropna(subset=['Latitude', 'Longitude'])

# Create the base map
base_map2022 = folium.Map(location=[39.8283, -98.5795], zoom_start=5)

# Prepare data for the heat map (latitude, longitude, donation amount)
heat_data = aggregated_donations[['Latitude', 'Longitude', 'Donation Amount']].values.tolist()

# Add the heat map to the base map
HeatMap(heat_data, radius=15).add_to(base_map2022)

# Save and display the map
base_map2022.save("donations_heatmap.html")
base_map2022
#this is the heat map from the 2022 donations dataset

In [69]:
# Filter for donations
data2 = df2023.dropna(subset=['City', 'Donation Amount'])  # Drop rows with missing data

# Aggregate donations by city
aggregated_donations2 = data2.groupby('City')['Donation Amount'].sum().reset_index()

# Initialize geolocator
geolocator = Nominatim(user_agent="donation_heatmap")

# Geocode function to get latitude and longitude for each city
def geocode_city(city, retries=3):
    for attempt in range(retries):
        try:
            location = geolocator.geocode(f"{city}, USA", timeout=10)  # Increase timeout
            if location:
                return location.latitude, location.longitude
            else:
                return None, None
        except GeocoderTimedOut:
            if attempt < retries - 1:
                time.sleep(2)  # Wait before retrying
                continue
            return None, None

# Add latitude and longitude columns to the aggregated donations DataFrame
aggregated_donations2[['Latitude', 'Longitude']] = aggregated_donations2['City'].apply(
    lambda city: pd.Series(geocode_city(city))
)

# Drop rows where geocoding failed
aggregated_donations2 = aggregated_donations2.dropna(subset=['Latitude', 'Longitude'])

# Create the base map
base_map2023 = folium.Map(location=[39.8283, -98.5795], zoom_start=5)

# Prepare data for the heat map (latitude, longitude, donation amount)
heat_data2 = aggregated_donations2[['Latitude', 'Longitude', 'Donation Amount']].values.tolist()

# Add the heat map to the base map
HeatMap(heat_data2, radius=15).add_to(base_map2023)

# Save and display the map
base_map2023.save("donations_heatmap_2023.html")
base_map2023